import {
  unoPlugin,
  sgsPlugin,
  ddzPlugin,
  checkersPlugin,
  flightPlugin,
} from "./builtin-rules";
export const gameCatalogue = {
  ddz: {
    rules: ddzPlugin,
    apiVersion: 1,
    name: "斗地主",
    category: "纸牌",
    description: "地主与农民",
    minPlayers: 3,
    maxPlayers: 3,
    module: 6544,
    team: false,
    symbol: "♠",
    ai: false,
    version: "1",
  },
  uno: {
    rules: unoPlugin,
    apiVersion: 1,
    name: "UNO",
    category: "纸牌",
    description: "颜色与数字",
    minPlayers: 2,
    maxPlayers: 8,
    module: 7707,
    team: false,
    ai: true,
    version: "1",
    symbol: "四色",
  },
  sgs: {
    rules: sgsPlugin,
    apiVersion: 1,
    name: "三国杀",
    category: "策略",
    description: "身份与武将",
    minPlayers: 2,
    maxPlayers: 8,
    module: 6749,
    team: true,
    ai: true,
    version: "1",
    symbol: "杀",
  },
  fxq: {
    rules: flightPlugin,
    apiVersion: 1,
    name: "飞行棋",
    category: "棋盘",
    description: "掷骰与飞跃",
    minPlayers: 2,
    maxPlayers: 4,
    module: 7448,
    team: false,
    ai: true,
    version: "1",
    symbol: "✈",
  },
  tq: {
    rules: checkersPlugin,
    apiVersion: 1,
    name: "跳棋",
    category: "棋盘",
    description: "连续跳跃与营地竞速",
    minPlayers: 2,
    maxPlayers: 6,
    module: 1621,
    team: false,
    ai: true,
    version: "1",
    symbol: "跳",
  },
} as const;
export type GameKind = keyof typeof gameCatalogue;
export const gameKinds = Object.keys(gameCatalogue) as [
  GameKind,
  ...GameKind[],
];
