(async () => {
  const waitFor = async read => {for (let i=0;i<600;i++) {const value=read(); if(value) return value; const error=document.querySelector(".compute-failure"); if(error) throw new Error(error.textContent); await new Promise(resolve=>setTimeout(resolve,100));} throw new Error(`等待超时：${read}`);};
  const button = text => [...document.querySelectorAll("button")].find(node=>node.textContent.trim()===text);
  try {
    await waitFor(()=>button("设置"));
    button("设置").click();
    await waitFor(()=>window.nativeCompleted?.settings);
    await waitFor(()=>JSON.parse(localStorage.getItem("onlinebg.preferences") || "{}").benchmarkVisible);
    await waitFor(()=>document.documentElement.dataset.theme==="dark");
    if (document.querySelector(".app-shell [role=dialog]")) throw new Error("设置仍是浏览器弹层");
    [...document.querySelectorAll(".game-card button")].find(node=>node.textContent.includes("连续跳跃与营地竞速")).click();
    await waitFor(()=>document.querySelector(".game-card.active")?.textContent.includes("连续跳跃与营地竞速"));
    button("创建房间").click();
    (await waitFor(()=>button("开始对局"))).click();
    await waitFor(()=>document.querySelector(".original-game"));
    const game=document.querySelector(".original-game");
    document.querySelector(".room-options > summary").click();
    (await waitFor(()=>[...document.querySelectorAll("button")].find(node=>node.textContent.includes("游戏操作")&&!node.disabled))).click();
    await waitFor(()=>window.nativeCompleted?.actions);
    await waitFor(()=>document.querySelector(".compute-status")?.textContent.includes("上次计算"));
    (await waitFor(()=>button("暂停 AI"))).click();
    if(document.querySelector(".room-avatars,.live-workspace")) throw new Error("牌桌仍拆分面板");
    await window.__TAURI_INTERNALS__.invoke("resize_main",{width:1000,height:720});
    await waitFor(()=>innerWidth<1100);
    button("聊天").click();
    await waitFor(()=>window.nativeCompleted?.chat);
    await waitFor(()=>document.querySelector(".chat-panel")?.textContent.includes("原生聊天测试"));
    await window.__TAURI_INTERNALS__.invoke("resize_main",{width:1440,height:900});
    await waitFor(()=>innerWidth>=1100&&!document.querySelector(".room-sidebar").hidden);
    if(!document.querySelector(".chat-panel").textContent.includes("原生聊天测试"))throw new Error("聊天切换丢失消息");
    window.nativeCompleted.chat=false;
    await window.__TAURI_INTERNALS__.invoke("resize_main",{width:1000,height:720});
    await waitFor(()=>window.nativeCompleted?.chat);
    button("聊天").click();
    button("新手引导").click();
    await waitFor(()=>window.nativeCompleted?.guide);
    await waitFor(()=>document.querySelectorAll("[data-guide-focus]").length===10);
    button("新手引导").click();
    if(document.querySelector(".original-game")!==game) throw new Error("辅助窗口重建游戏");
    button("关于").click();
    await waitFor(()=>window.nativeCompleted?.about);
    if (!document.querySelector(".original-game")) throw new Error("关闭关于窗口退出房间");
    button("对局记录").click();
    await waitFor(()=>window.nativeCompleted?.records);
    if(document.querySelector(".original-game")!==game) throw new Error("回放窗口影响主牌桌");
    await window.__TAURI_INTERNALS__.invoke("report", {result:`PASS: native decorated/resizable settings, actions, about, replay windows; main room survives auxiliary close; complete table; native narrow chat and guide; native multi-worker AI; ${navigator.userAgent}`});
  } catch(error) {await window.__TAURI_INTERNALS__.invoke("report", {result:`FAIL: ${error}\n${document.body.innerText}`});}
})();
